import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AosInit from "@/components/ui/aos";
import GlobalState from "./context";
import {QueryProviders} from "@/components/query-provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AosInit />
      <body
        className={`antialiased min-h-screen`}
      >
        <GlobalState>
          <QueryProviders>
            {children}
          </QueryProviders>
        </GlobalState>
      </body>
    </html>
  );
}
