import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AosInit from "@/components/aos";
import GlobalState from "./context";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AosInit />
      <body
        className={`antialiased min-h-screen`}
      >
        <GlobalState>
          {children}
        </GlobalState>
      </body>
    </html>
  );
}
